title: Zachary R. Hanna
theme: jekyll-theme-cayman
google_analytics: UA-117462623-1
#email: zachanna@berkeley.edu
#url: "https://zrhanna.github.io"
#name: Zachary R. Hanna
#permalink: /blog/:year/:month/:day/:title
# Build settings
#markdown: kramdown
#plugins:
#  - jekyll-seo-tag
